# Generated by Django 5.2.9 on 2025-12-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
