# Build Stage
FROM node:22-alpine AS build

WORKDIR /app

ARG API_URL=https://factora.novadev-edge.io

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ .

RUN find . -type f -name "*.ts" -exec sed -i "s|http://localhost:8000|${API_URL}|g" {} +

RUN npm run build -- --configuration=production

FROM nginx:alpine

COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]