# Generated by Django 5.2.9 on 2025-12-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="users.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("tenant", "customer_number")},
        ),
    ]
