# Generated by Django 5.2.9 on 2025-12-16 22:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("xrechnung", "XRechnung (XML)"),
                            ("zugferd", "ZUGFeRD (PDF)"),
                        ],
                        default="zugferd",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("final", "Finalisiert"),
                            ("sent", "Versendet"),
                            ("paid", "Bezahlt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("leitweg_id", models.CharField(blank=True, max_length=50)),
                ("buyer_reference", models.CharField(blank=True, max_length=100)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("payment_terms", models.TextField(blank=True)),
                ("xml_file", models.FileField(blank=True, upload_to="invoices/xml/")),
                ("pdf_file", models.FileField(blank=True, upload_to="invoices/pdf/")),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("archive_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-invoice_date", "-invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                ("sku", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(max_length=500)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.000"), max_digits=10
                    ),
                ),
                ("unit", models.CharField(default="H87", max_length=3)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("19.00"), max_digits=5
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "db_table": "invoice_items",
                "ordering": ["position"],
            },
        ),
    ]
