# Generated by Django 5.2.9 on 2025-12-17 21:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1. Zahlungserinnerung"),
                            (2, "2. Mahnung"),
                            (3, "3. Mahnung (letzte)"),
                        ],
                        default=1,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("sent_to", models.EmailField(max_length=254)),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "db_table": "invoice_reminders",
                "ordering": ["-sent_at"],
            },
        ),
    ]
