# Generated by Django 5.2.9 on 2025-12-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data', models.BinaryField()),
                ('data_hash', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='archive', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Rechnungsarchiv',
                'verbose_name_plural': 'Rechnungsarchive',
                'db_table': 'invoice_archives',
            },
        ),
    ]
