# Generated by Django 5.2.9 on 2025-12-16 22:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("H87", "Stück"),
                            ("HUR", "Stunde"),
                            ("DAY", "Tag"),
                            ("MON", "Monat"),
                            ("KGM", "Kilogramm"),
                            ("MTR", "Meter"),
                            ("LTR", "Liter"),
                            ("C62", "Einheit"),
                        ],
                        default="H87",
                        max_length=3,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        choices=[
                            (Decimal("19.00"), "19% (Standard)"),
                            (Decimal("7.00"), "7% (Ermäßigt)"),
                            (Decimal("0.00"), "0% (Steuerfrei)"),
                        ],
                        decimal_places=2,
                        default=Decimal("19.00"),
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["name"],
            },
        ),
    ]
